// cart actions
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const EMPTY_CART = 'EMPTY_CART';

// wishList actions
export const ADD_ITEM_TO_WISHLIST = 'ADD_ITEM_TO_WISHLIST';
export const REMOVE_ITEM_FROM_WISHLIST = 'REMOVE_ITEM_FROM_WISHLIST';
export const FETCH_WISHLIST_SUCCESS = 'FETCH_WISHLIST_SUCCESS';
export const FETCH_WISHLIST_ACTIVE = 'FETCH_WISHLIST_ACTIVE';

// order actions
export const CREATE_NEW_ORDER = 'CREATE_NEW_ORDER';
export const REMOVE_ORDER = 'REMOVE_ORDER';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_ACTIVE = 'FETCH_ORDERS_ACTIVE';

// User actions
export const REGISTER_NEW_USER = 'REGISTER_NEW_USER';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';

// Info Actions
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const ADD_MESSAGE = 'ADD_MESSAGE';
